### ISSUE TITLE
Missing Logo.png File

### ISSUE THREAD

**Issue by TerabyteTiger** [VickiLanger/code-questions-bot#14]
**Describe the bug**
Currently on the Github page, there is a `img` tag in the Navbar with `src="logo.png"`. 

It looks like the logo file wasn't uploaded to the repo. 

**To Reproduce**
1. Go to https://vickilanger.github.io/code-questions-bot/
2. Notice the Logo is a broken image link in the nav bar

**Expected behavior**
The Logo should be displayed.

**Screenshots**

![image](https://user-images.githubusercontent.com/16465776/74361897-ad3ad000-4d95-11ea-8cc5-b06b8a656d30.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge (Chromium Beta)
 - Version  80.0.361.50

**Comment by VickiLanger** [comment]
Yup, totally broken. Guess I never added the logo. I'll add it in my next push.  Thanks for the issue!

**Comment by VickiLanger** [comment]
Logo uploaded and verified it looks good.
![Screen Shot 2020-02-17 at 11 56 53 AM](https://user-images.githubusercontent.com/46823403/74673127-a25cb280-517c-11ea-97f7-31dfd8077861.png)

@12vanblart Thanks for reporting this issue!
