### ISSUE TITLE
Add polls

### ISSUE THREAD

**Issue by VickiLanger** [VickiLanger/code-questions-bot#16]
Add poll-based questions

Reference stuff:
@Roachbones was able to tweets polls with https://github.com/Roachbones/is-it-valid/blob/master/poll_tweeter.py

---
*Don't forget to follow the bot on [Twitter](https://www.twitter.com/CodeQBot) to see the hard work you put in.*

**Comment by ShubhamPalriwala** [comment]
Hey, I might have a long shot at this but would love to try it out !

**Comment by VickiLanger** [comment]
Go for it. I'd love to see what you come up with. I'm happy to answer any questions you have about the code that's already there. I put in this issue thinking it was a long shot. I think @RoachBones was actually opening a firefox instance to get around the lack of polling in the twitter api

**Comment by ShubhamPalriwala** [comment]
Can we use the Twitter Ads-API ? Apparently, they have a direct method !

**Comment by VickiLanger** [comment]
@ShubhamPalriwala
Oh! I didn't realize that was a thing. Let me take a look and see what it requires from me. Thanks for seeking that out. Looks like all I have to do it apply for more keys. I submitted the application. It said it could take up to 7 days to come back.

I set up `tweet_poll.py` as it requires different twitter keys. 

https://developer.twitter.com/en/products/twitter-ads-api

**Comment by ShubhamPalriwala** [comment]
Alright so I'll set up the polls API in that file !

**Comment by ShubhamPalriwala** [comment]
@VickiLanger Please have a look at PR #27

**Comment by ShubhamPalriwala** [comment]
Since the PR is merged, Please close the issue @VickiLanger !
