### ISSUE TITLE
Stop the repeating questions!

### ISSUE THREAD

**Issue by VickiLanger** [VickiLanger/code-questions-bot#17]
**Is your feature request related to a problem? Please describe.**
Some questions are being asked repeatedly

**Describe the solution you'd like**
I'd like the questions to not be repeated so often

**Describe alternatives you've considered**
- read [docs on random()](https://docs.python.org/3/library/random.html) to see if there is a better way
- remove each question from the list until they've all been asked, then add them back in
- track questions being in a database

**Additional context**
https://twitter.com/vicki_langer/status/1230321697439571969?s=20

---
*Don't forget to follow the bot on [Twitter](https://www.twitter.com/CodeQBot) to see the hard work you put in.*

**Comment by VickiLanger** [comment]
This repo used logs to stop repeating things. Maybe do it like they did
https://github.com/joaquinlpereyra/twitterImgBot/blob/master/twitterbot.py

**Comment by kandasamyc** [comment]
Can I work on this?

**Comment by VickiLanger** [comment]
@SamC302 that would be great. Do you know how you're going to tackle it?

**Comment by kandasamyc** [comment]
I'll try the logs idea, and I think I've gotten that mostly sorted out. Write to a file in the questions folder, and just choose a question that wasn't already asked by checking if it was in the file.

It also looks like I have to modify the imports in questions as they currently don't seem to work. I plan to just make sure they are actually importing from the questions directory.

**Comment by VickiLanger** [comment]
You're right! They don't work. I broke them this weekend when I moved all the questions files to the folder. I just haven't looked up how to pull from the directory.
